## Análise de Dados - Aula 01
Data: 12/02/2026

In [1]:
import pandas as pd
from datetime import datetime

date = datetime.now()

In [2]:
print(date)

2026-02-19 09:16:33.465353

Estamos criando uma collection de dados para gerar um Dataframe

In [3]:
dados = {
    'ID': [1, 2, 3, 4, 5],
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'CPF': ['123.456.789-00', '987.654.321-00', '111.222.333-44', '555.666.777-88', '999.888.777-66'],
}

Tranformando a collection em um DataFrame

In [4]:
dt = pd.DataFrame(dados)

Imprime na tela o DataFrame

In [5]:
dt.head()

   ID     Nome             CPF
0   1    Alice  123.456.789-00
1   2      Bob  987.654.321-00
2   3  Charlie  111.222.333-44
3   4    David  555.666.777-88
4   5      Eve  999.888.777-66

Realizando transformação nos nomes das pessoas (UPPER)

In [6]:
dt['Nome'] = dt['Nome'].str.upper()

In [7]:
dt.head()

   ID     Nome             CPF
0   1    ALICE  123.456.789-00
1   2      BOB  987.654.321-00
2   3  CHARLIE  111.222.333-44
3   4    DAVID  555.666.777-88
4   5      EVE  999.888.777-66

Filtrando os IDs 2, 3 e 4
<br>
(Data da OBS: 19/02/2026) Obs.: Sempre que for necessário realizar o filtro nos dados, armazenar o resultado em uma variável separada. Isso evita que os dados originais se percam.

In [8]:
dt_filtrado = dt[(dt['ID'] >= 2) & (dt['ID'] <= 4)]

In [9]:
dt_filtrado.head()

   ID     Nome             CPF
1   2      BOB  987.654.321-00
2   3  CHARLIE  111.222.333-44
3   4    DAVID  555.666.777-88

In [10]:
dt.head()

   ID     Nome             CPF
0   1    ALICE  123.456.789-00
1   2      BOB  987.654.321-00
2   3  CHARLIE  111.222.333-44
3   4    DAVID  555.666.777-88
4   5      EVE  999.888.777-66